apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: {{ .Values.Namespace }}
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
