apiVersion : v1
kind: Service

metadata:
  name: broker-service
  labels:
    app: broker-service
  namespace: bootcamp

spec:
  clusterIP: None
  ports:
  - name : broker
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name : metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app: broker