apiVersion : apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
  namespace: bootcamp

spec:
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        imagePullPolicy: IfNotPresent
        image: calgor/balebroker:v8
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_TYPE
            value: "scylla"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        command:
          - "/bin/bash"
          - "-c"
          - "./scripts/wait-for-it.sh -t 0 scylla:9042 && go run ./api/proto/server/main.go"
  replicas: 1
    