apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
  namespace: bootcamp

spec:
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        imagePullPolicy: IfNotPresent
        image: calgor/balebroker:v15
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_TYPE
            value: "scylla"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits:
            cpu: "0.3"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
  replicas: 2
